services:
  - type: web
    name: food_project-web-service
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: |
      python manage.py migrate  
      uvicorn food_project.asgi:application --host 0.0.0.0 --port 8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: food_project.settings
      - key: DATABASE_URL
        value: postgres://postgres:db%40123@localhost:5432/food_db
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        value: adpass
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@email.com