# Generated by Django 5.0.3 on 2024-03-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desrp', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='gallery')),
                ('offers', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='showoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_show', models.ImageField(upload_to='food_image')),
            ],
        ),
    ]
