# Generated by Django 5.0.3 on 2024-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email_address',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
