# Generated by Django 5.0.3 on 2024-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='show_vid')),
            ],
        ),
    ]
